name: vapor-master
version: '0.2'
grade: stable
confinement: strict
summary: RosHub Vapor Master
description: RosHub Vapor Master
icon: icons/roshub_vector_logo-256x256.png
architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

  - build-on: armhf
    run-on: armhf

  - build-on: arm64
    run-on: arm64

apps:
  vapor-master:
    command: npx vapor-master
    plugs: [network, network-bind]
    daemon: simple

parts:
  vapor-master:
    source: .
    plugin: nodejs
    node-engine: "8.12.0"
    node-package-manager: "yarn"
    npm-run: ["prepare-snapcraft"]
